### ISSUE TITLE
xlsx_parser: Get user-visible worksheet names

### ISSUE THREAD

**Issue by jeffreykemp** [jeffreykemp/sample#2]
The worksheet names returned by the API are internal names, e.g. "sheet1", "sheet2", etc.

Add a function to return a list of worksheets along with their user-visible label.

**Comment by limingtieu** [comment]
Hi Jeffrey,
I want to use this package on Apex 4.2. But I'm getting a compile error identifier 'T_ARRAY_VARCHAR2' must be declared.
Where is T_ARRAY_VARCHAR2 declared?

**Comment by jeffreykemp** [comment]
The type is defined in https://github.com/jeffreykemp/sample/blob/master/xlsx_parser/types.sql

**Comment by limingtieu** [comment]
Sorry did not see that file. I guess it was something like that but wanted to be sure. Thank you!
