### ISSUE TITLE
How can I adapt Carsten Czarski's in 21.2?

### ISSUE THREAD

**Issue by EdissonG** [jeffreykemp/sample#4]
I tried to implement the one from Carsten Czarski, but I think I don't load the whole body of the package because it doesn't have an end and the error pops up. What I see is that here you make a package zip_util_pkg.get_file() and the post uses apex_zip.get_file_content(), what is the difference? I understand it is by version as a package deprecated by version, I am on 21.2.

I wrote to him on twitter (he follows this repository too), but I didn't know they had a repository and they rely on his post.

What I understand is that I can have several files in the .zip file and it will load them all in one?

Greetings, Edisson.

**Comment by jeffreykemp** [comment]
If you're on 21.2, you can use the new APEX_DATA_PARSER API which handles XLSX files.

https://docs.oracle.com/en/database/oracle/application-express/21.2/aeapi/APEX_DATA_PARSER.html#GUID-07E9397C-DF26-40F7-AC73-F46961E1088A
